package constants

// log_templates.go 集中定义所有日志模板，业务字段变更必须同步修改此处与调用处。
const (
	LogServerStart     = "server starting env=%s port=%s"
	LogServerStop      = "server stopping"
	LogDBConnected     = "mongodb connected db=%s"
	LogRedisConnected  = "redis connected addr=%s"
	LogMinIOConnected  = "minio connected endpoint=%s bucket=%s"
	LogConfigLoaded    = "config loaded env=%s"
	LogRequestIn       = "incoming request request_id=%s method=%s path=%s"
	LogRequestDone     = "request done request_id=%s method=%s path=%s status=%d latency_ms=%d"
	LogUserRegistered  = "user registered user_id=%s username=%s"
	LogUserLogin       = "user login user_id=%s username=%s"
	LogUserFollow      = "user follow follower_id=%s followee_id=%s"
	LogUserUnfollow    = "user unfollow follower_id=%s followee_id=%s"
	LogPetCreated      = "pet created pet_id=%s owner_id=%s name=%s"
	LogPetUpdated      = "pet updated pet_id=%s owner_id=%s"
	LogPostCreated     = "post created post_id=%s author_id=%s type=%s status=%s"
	LogPostRejected    = "post rejected post_id=%s reason=%s"
	LogPostApproved    = "post approved post_id=%s"
	LogPostLiked       = "post liked post_id=%s user_id=%s"
	LogPostFavorited   = "post favorited post_id=%s user_id=%s"
	LogPostForwarded   = "post forwarded post_id=%s user_id=%s"
	LogCommentAdded    = "comment added comment_id=%s post_id=%s author_id=%s"
	LogMeetupCreated   = "meetup created meetup_id=%s creator_id=%s city=%s"
	LogMeetupJoined    = "meetup joined meetup_id=%s user_id=%s"
	LogMeetupCancelled = "meetup cancelled meetup_id=%s user_id=%s"
	LogMeetupStatus    = "meetup status meetup_id=%s status=%s"
	LogMeetupConflict  = "meetup join conflict target_meetup_id=%s user_id=%s conflict_meetup_id=%s conflict_title=%s"
	LogChatSent        = "chat message sent message_id=%s from_id=%s to_id=%s type=%s"
	LogAuditCreated    = "audit log created user_id=%s action=%s resource=%s"
	LogTokenIssued     = "jwt token issued user_id=%s role=%s"
	LogSensitiveHit    = "sensitive word hit post_id=%s word=%s"
	LogMediaUploaded   = "media uploaded object=%s size=%d"
	LogRateLimited     = "rate limited ip=%s path=%s"
	LogRecoveryPanic   = "panic recovered request_id=%s error=%v"
	LogSeedStarted     = "seed data started"
	LogSeedDone        = "seed data done inserted_users=%d inserted_pets=%d inserted_posts=%d"
)
